name: Rust

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest
        env:
            FIRST_NAME: Mona

        steps:
            - uses: actions/checkout@v2
            - name: Version Info
              run: rustup --version && rustc --version && cargo --version
            - name: Add clippy and fmt components
              run: rustup component add clippy rustfmt
            - name: Lint
              run: cargo fmt -- --check && cargo clippy --all-targets --all-features -- -D warnings
            - name: Run tests
              run: cargo test --all-features
